import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./RootProvider";

const inter = Poppins({
  subsets: ["devanagari"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
    </body>
  </html>
);
export default RootLayout;
